error: working on patch for weird windows bug
Windows bug, upon fetching a certain resource (don't know what yet),
will cause the server to crash.

Possible causes:

- Insufficient mime types which are being sent.
- Header for size of file not being set
- Other?